version: "3.7"
services:
  java:
    build:
      context: .
      dockerfile: java.Dockerfile

  react:
    build:
      context: .
      dockerfile: react.Dockerfile

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - 80:80

  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: hha
      POSTGRES_PASSWORD: HHAdatabase
      POSTGRES_DB: hha_db

